import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import Providers from './providers';
import './globals.css';
import Link from 'next/link';

const geistSans = Geist({
   variable: '--font-geist-sans',
   subsets: ['latin'],
});

const geistMono = Geist_Mono({
   variable: '--font-geist-mono',
   subsets: ['latin'],
});

export const metadata: Metadata = {
   title: 'Create Next App',
   description: 'Generated by create next app',
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang='en'>
         <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
            <div className='text-center w-full'>
               see dashboard only testing mode{' '}
               <Link
                  className='text-blue-700 font-bold text-center w-full '
                  href={'/dashboard'}>
                  Dashboard
               </Link>
            </div>
            <Providers>{children}</Providers>F
         </body>
      </html>
   );
}
